name: VineriumCore
version: '1.0'
author: SaintQd
main: org.saintqd.vineriumcore.VineriumCore
description: VineriumCore Plugin
api-version: '1.21.8'
dependencies:
  server:
    VineriumLib:
      load: BEFORE
      required: true
    PlaceholderAPI:
      load: BEFORE
      required: false
    Vault:
      load: BEFORE
      required: false
    CMI:
      load: BEFORE
      required: false
    DiscordSRV:
      load: BEFORE
      required: false
    WorldGuard:
      load: BEFORE
      required: false
    LiteBans:
      load: BEFORE
      required: false
    LuckPerms:
      load: BEFORE
      required: false