name: VineriumCore
version: 1.0
author: SaintQd
main: org.saintqd.vineriumcore.VineriumCore
api-version: 1.21.8
depend: [VineriumLib]
softdepend:
  - PlaceholderAPI
  - CMI
  - DiscordSRV
  - WorldGuard
  - LiteBans
  - LuckPerms
permissions:
  vineriumcore.admin:
    description: Access to admin commands.
    default: op