Language: ru_ru
Messages:
  Enabled: true
  Join:
    Enabled: true
    Format: ' <gradient:#EF97D1:#AA68F6>[+] • [message]'
  DefaultJoin:
    Enabled: true
    Format: ' <gradient:#EF97D1:#AA68F6>[+] • * зашёл поиграть'
  Leave:
    Enabled: true
    Format: ' <gradient:#AFF5FF:#E7A6FF>[-] • [message]'
  DefaultLeave:
    Enabled: true
    Format: ' <gradient:#AFF5FF:#E7A6FF>[-] • * вышел из игры'
  FirstJoin:
    Enabled: true
    Format: ' <#82ECB4>[❤] • * впервые на сервере'
  MaxLength: 100
  NicknameFormat: '%player_name% <white>%luckperms_suffix%</white>'
  RightClickNickname:
    Enabled: true
    HideInvisible: true
    SneakingAllowed: false
    AlwaysShowGamemodes:
      - 'CREATIVE'
      - 'SPECTATOR'
    Format: '%luckperms_prefix%*'
  Death:
    Enabled: true
    Format: '<#E02626>[<white>ꐜ</white>] •</#E02626> <#D25454>*'
    PlayerName: '<gold>* <white>%luckperms_suffix%</white></gold>'
  Advancement:
    Enabled: true
    Format: '<#9D41E0>[<light_purple>⚝</light_purple>] •</#9D41E0> <#8ED9E3>*'
    PlayerName: '<gold>* <white>%luckperms_suffix%</white></gold>'
    ShowTypes:
      - CHALLENGE
    AlwaysShowNamespaces:
      - 'minecraft'
VillagerOptimizer:
  Enabled: true
  DisableUnoptimizedTrades: true
  InteractMaterial: SHEARS
  RestockInterval: 1000
  RestockSound: entity.villager.celebrate
  InteractSound: entity.villager.hurt
DynamicMobCaps:
  Enabled: true
  Categories:
    MONSTER:
      ALL:
       0: 25
       15: 20
       25: 15
       35: 10
       45: 5
    ANIMAL:
      ALL:
        0: 8
        15: 6
        25: 4
        35: 2
    WATER_ANIMAL:
      ALL:
        0: 8
        15: 6
        25: 4
        35: 2
    WATER_AMBIENT:
      ALL:
        0: 8
        15: 6
        25: 4
        35: 2
    WATER_UNDERGROUND_CREATURE:
      ALL:
        0: 8
        15: 6
        25: 4
        35: 2
    AXOLOTL:
      ALL:
        0: 5
        15: 4
        25: 3
        35: 2
        45: 1
    AMBIENT:
      ALL:
        0: 3
        25: 2
        35: 1
PvPMode:
  Enabled: true
  Placeholder: '⚔ '
  MinRadiusWithoutPlayers: 50
TimersCooldown:
  entityNotEnabledPvp: 200
  damagerNotEnabledPvp: 200
  pvpToggleCooldown: 6000
RepairCostFix:
  Enabled: true
  Force: false
DiscordSRV:
  MessageFormats:
    donate_purchase_message:
      Webhook:
        Enabled: false
        AvatarUrl: '%botavatarurl%'
        Name: '%botname%'
      Content: ''
      Embed:
        Enabled: true
        Color: '#999900'
        Author:
          ImageUrl: '%embedavatarurl%'
          Name: ᴩᴜʀᴄʜᴀꜱᴇ
          Url: ''
        ThumbnailUrl: ''
        Title:
          Text: ''
          Url: ''
        Description: |-
          ▸ Игрок %username% приобрёл услугу: {1}
          ▸ Стоимость: {2}
          ▸ Время: {time}
        Fields: []
        ImageUrl: ''
        Footer:
          Text: ''
          IconUrl: ''
        Timestamp: false