$onceKeys:
  - 'DynamicMobCaps.Categories'
  - 'DynamicDistance.View'
  - 'DynamicDistance.Simulation'
  - 'OreAlerts.Materials'
  - 'Tweaks.VillagerManualBreed.Items'
  - 'Tweaks.PortalRedirect.Worlds'
  - 'Tweaks.CauldronTransform.TransformList'
  - 'CustomPortals.List'
Language: ru_ru
Messages:
  Enabled: true
  Join:
    Enabled: true
    Format: ' <gradient:#EF97D1:#AA68F6>[+] • [message]'
  DefaultJoin:
    Enabled: true
    Format: ' <gradient:#EF97D1:#AA68F6>[+] • * зашёл поиграть'
  Leave:
    Enabled: true
    Format: ' <gradient:#AFF5FF:#E7A6FF>[-] • [message]'
  DefaultLeave:
    Enabled: true
    Format: ' <gradient:#AFF5FF:#E7A6FF>[-] • * вышел из игры'
  FirstJoin:
    Enabled: true
    Format: ' <#82ECB4>[❤] • * впервые на сервере'
  MaxLength: 100
  NicknameFormat: '%player_name% <white>%luckperms_suffix%</white>'
  Me:
    Distance: 25
    Format: '<#EF97D1>* <#E7A6FF>%name% <#EF97D1>%message%'
  Try:
    Distance: 25
    Format: '<#EF97D1>* <#E7A6FF>%name% <#EF97D1>%message% [<reset>%result%<#EF97D1>]'
  RightClickNickname:
    Enabled: true
    HideInvisible: true
    SneakingAllowed: false
    AlwaysShowGamemodes:
      - 'CREATIVE'
      - 'SPECTATOR'
    Format: '%luckperms_prefix%*'
  Death:
    Enabled: true
    Format: '<#E02626>[<white>ꐜ</white>] •</#E02626> <#D25454>*'
    PlayerName: '<gold>* <white>%luckperms_suffix%</white></gold>'
  Advancement:
    Enabled: true
    Format: '<#9D41E0>[<light_purple>⚝</light_purple>] •</#9D41E0> <#8ED9E3>*'
    PlayerName: '<gold>* <white>%luckperms_suffix%</white></gold>'
    ShowTypes:
      - CHALLENGE
    AlwaysShowNamespaces:
      - 'minecraft'
StarterHints:
  Join: -1
  Timer: 24000
  MaxPlaytime: 18000000
PlayerLimit:
  Enabled: true
  Limit: 100
DynamicParamsUpdateTime: 12000
DynamicMobCaps:
  Enabled: true
  Categories:
    MONSTER:
      ALL:
        '0': 25
        '20': 20
        '40': 15
        '60': 10
        '75': 5
    ANIMAL:
      ALL:
        '0': 8
        '20': 6
        '40': 4
        '60': 2
    WATER_ANIMAL:
      ALL:
        '0': 8
        '20': 6
        '40': 4
        '60': 2
    WATER_AMBIENT:
      ALL:
        '0': 8
        '20': 6
        '40': 4
        '60': 2
    WATER_UNDERGROUND_CREATURE:
      ALL:
        '0': 3
        '25': 2
        '50': 1
        '75': 6
    AXOLOTL:
      ALL:
        '0': 5
        '20': 4
        '40': 3
        '60': 2
        '75': 1
    AMBIENT:
      ALL:
        '0': 3
        '20': 2
        '40': 1
DynamicDistance:
  Enabled: true
  View:
    ALL:
      0: 8
      30: 7
      60: 6
      80: 5
      100: 4
  Simulation:
    ALL:
      0: 7
      30: 6
      60: 5
      80: 4
      100: 3
PvPMode:
  Enabled: true
  Placeholder: '⚔ '
  MinRadiusWithoutPlayers: 50
TimersCooldown:
  entity_not_enabled_pvp: 200
  damager_not_enabled_pvp: 200
  pvp_toggle_cooldown: 6000
Tweaks:
  RepairCostFix:
    Enabled: true
    Force: false
  GrindstoneDisenchant: true
  AgeLock:
    Enabled: true
    Item: POISONOUS_POTATO
    RemoveItem: true
  VillagerOptimizer:
    Enabled: true
    DisableUnoptimizedTrades: true
    InteractMaterial: SHEARS
    RestockInterval: 1000
    RestockSound: entity.villager.celebrate
    InteractSound: entity.villager.hurt
    InjectTradesOnOptimize:
      minecraft:toolsmith:
        - 'EMERALD:1,AIR:1,IRON_INGOT:4'
  VillagerManualBreed:
    Enabled: true
    Cooldown: 1200
    Items:
      BREAD: 6
      CARROT: 24
      POTATO: 24
      BEETROOT: 24
  CopperGolem:
    Enabled: true
    InteractMaterials:
      - REDSTONE_TORCH
      - END_ROD
    InteractSound: entity.iron_golem.repair
    MaxPerPlayer: 2
    MaxPerChest: 1
  AnvilRepair:
    Enabled: true
    RepairMaterial: IRON_BLOCK
    RepairSound: entity.iron_golem.repair
  PortalRedirect:
    Enabled: false
    Worlds:
      test:
        Commands:
          - 'cmi tppos %player_name% 100.0 100.0 100.0'
  MaceDenier:
    Enabled: false
    CustomNames:
      - 'Элдрик, Главный кузнец Незера'
  ItemLock:
    Enabled: true
    Materials:
      - 'NETHERITE_UPGRADE_SMITHING_TEMPLATE'
      - 'FILLED_MAP'
    BlockedCommands:
      - 'draw'
  EntityPortalBlock:
    Enabled: false
    EnabledNether: false
    EnabledEnd: true
    Remove: true
  HideDeathMessages:
    Enabled: true
    MinDeaths: 3
    Period: 12000
  CauldronTransform:
    Enabled: true
    RequireWater: true
    TransformList:
      WHITE_CONCRETE_POWDER: WHITE_CONCRETE
      LIGHT_GRAY_CONCRETE_POWDER: LIGHT_GRAY_CONCRETE
      GRAY_CONCRETE_POWDER: GRAY_CONCRETE
      BLACK_CONCRETE_POWDER: BLACK_CONCRETE
      BROWN_CONCRETE_POWDER: BROWN_CONCRETE
      RED_CONCRETE_POWDER: RED_CONCRETE
      ORANGE_CONCRETE_POWDER: ORANGE_CONCRETE
      YELLOW_CONCRETE_POWDER: YELLOW_CONCRETE
      LIME_CONCRETE_POWDER: LIME_CONCRETE
      GREEN_CONCRETE_POWDER: GREEN_CONCRETE
      CYAN_CONCRETE_POWDER: CYAN_CONCRETE
      LIGHT_BLUE_CONCRETE_POWDER: LIGHT_BLUE_CONCRETE
      BLUE_CONCRETE_POWDER: BLUE_CONCRETE
      PURPLE_CONCRETE_POWDER: PURPLE_CONCRETE
      MAGENTA_CONCRETE_POWDER: MAGENTA_CONCRETE
      PINK_CONCRETE_POWDER: PINK_CONCRETE
      DIRT: MUD
Compatibility:
  LiteBans:
    Enabled: true
    CommandsOnBan:
      - 'vindiscord addrole %player_name% 1307640043975737434'
      - 'vindiscord removerole %player_name% 727633442950479873'
    CommandsOnTempBan:
      - 'vindiscord addrole %player_name% 1307640043975737434 %time%ms'
      - 'vindiscord removerole %player_name% 727633442950479873 %time%ms'
    CommandsOnUnban:
      - 'vindiscord addrole %player_name% 727633442950479873'
      - 'vindiscord removerole %player_name% 1307640043975737434'
    CommandsOnMute: []
    CommandsOnTempMute: []
    CommandsOnUnmute: []
  LuckPerms:
    Enabled: true
    VipGroupName: 'vip'
AccountTransfer:
  PlayerDataPath: 'world'
  LuckPerms: true
  Advancements: true
  Stats: true
  Inventory: true
  EnderChest: true
  Money: true
  CMI: true
  Commands:
    - 'cmi tp %new_player_name% %old_player_name%'
OreAlerts:
  Enabled: true
  Materials:
    DEEPSLATE_DIAMOND_ORE:
      Threshold: 25
      Color: "<aqua>"
    DIAMOND_ORE:
      Threshold: 25
      Color: "<aqua>"
    ANCIENT_DEBRIS:
      Threshold: 7
      Color: "<red>"
  HoverCommand: 'cmi tp {1}'
  TimeToThreshold: 12000
  Sound: "entity.player.levelup,2"
CommandFilter:
  Enabled: true
  Regex:
    - '[@#ꐙꐔꐒꐓꐕꐐꐑ᠀ᘐ҂ォ୭⩩⇴㚼⼓⏍ꗃ૪⟆ᦔリ꒰⩇↹୭ରୁ୦ದಷಸಬನರಣಹಗಪಶೋಳುೀ水小漢对頁字海陆美도연강대낮ꐖꐗꐘꐚꐛꐜꐝꐞꐟꐠꐡꐢꐣꐤꐥꐦꐧꐨꐩꐪ]'
Mailbooks:
  TextPrefix: ''
  ExpireTime: 12096000
  MailbookKey: ''
DisableDrops:
  Enabled: false
  Materials:
    - COAL_ORE
    - DEEPSLATE_COAL_ORE
    - IRON_ORE
    - DEEPSLATE_IRON_ORE
    - COPPER_ORE
    - DEEPSLATE_COPPER_ORE
    - EMERALD_ORE
    - DEEPSLATE_EMERALD_ORE
    - GOLD_ORE
    - DEEPSLATE_GOLD_ORE
    - REDSTONE_ORE
    - DEEPSLATE_REDSTONE_ORE
    - LAPIS_ORE
    - DEEPSLATE_LAPIS_ORE
    - DIAMOND_ORE
    - DEEPSLATE_DIAMOND_ORE
    - ANCIENT_DEBRIS
CustomPortals:
  Enabled: true
  List:
    WAXED_COPPER_BLOCK:
      Amount: 4
      Commands: []
    COPPER_BLOCK:
      Amount: 4
      Commands: []
ConfirmationStatus:
  Format: '✦ '